version: 2.1
executors:
  build:
    docker:
      - image: circleci/golang:1.13
  deploy:
    docker:
      - image: circleci/golang:1.13

jobs:
  build:
    executor:
      name: build
    steps:
      - checkout
      - run:
          name: linting
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
            golangci-lint run
      - run:
          name: build
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app cmd/main.go
  deploy:
    executor:
      name: deploy
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            echo "deploy"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          name: test_build
          filters:
            branches:
              only: /.*/
      - deploy:
          name: test_deploy
          filters:
            branches:
              only: /.*/
          requires:
            - test_build